CREATE TABLE CONSULTA
(
	CODIGO INTEGER NOT NULL,
	DT_CONSULTA DATE DEFAULT CURRENT_DATE NOT NULL,
	HR_CONSULTA TIME DEFAULT LOCALTIME NOT NULL,
	VALOR NUMERIC(15, 3) DEFAULT 0 NOT NULL,
	PACIENTE_CODIGO INTEGER NOT NULL,
	MEDICO_CODIGO INTEGER NOT NULL,
	
	CONSTRAINT PK_CONSULTA PRIMARY KEY(CODIGO),
	
	CONSTRAINT FK_PACIENTE_CONSULTA FOREIGN KEY(PACIENTE_CODIGO) REFERENCES PACIENTE(CODIGO),
	CONSTRAINT FK_MEDICO_CONSULTA FOREIGN KEY(MEDICO_CODIGO) REFERENCES MEDICO(CODIGO)
);