CREATE TABLE DEPENDENTE
(
	SEQUENCIA SMALLINT NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	PACIENTE_CODIGO INTEGER NOT NULL,
	
	CONSTRAINT PK_DEPENDENTE PRIMARY KEY(PACIENTE_CODIGO, SEQUENCIA), /* CHAVE PRIMARIA COMPOSTA, POIS DEPENDENTE É UMA ENTIDADE FRACA */
	
	CONSTRAINT FK_PACIENTE_DEPENDENTE FOREIGN KEY(PACIENTE_CODIGO) REFERENCES PACIENTE(CODIGO)
);