CREATE TABLE REGISTRO
(
	DT_REGISTRO DATE NOT NULL,
	MATRICULA VARCHAR(20) NOT NULL,
	CONVENIO_CODIGO INTEGER NOT NULL,
	PACIENTE_CODIGO INTEGER NOT NULL,
	
	CONSTRAINT PK_REGISTRO PRIMARY KEY(CONVENIO_CODIGO, PACIENTE_CODIGO),
	
	CONSTRAINT FK_PACIENTE_REGISTRO FOREIGN KEY(PACIENTE_CODIGO) REFERENCES PACIENTE(CODIGO),
	CONSTRAINT FK_CONVENIO_REGISTRO FOREIGN KEY(CONVENIO_CODIGO) REFERENCES CONVENIO(CODIGO)
);